### ISSUE TITLE
[Feature Request] Slider with min, max and step sizes.

### ISSUE THREAD

**Issue by JohnEdwa** [RuneMasterGaming/RiskOfOptions#2]
I noticed that you are making a rewrite, so I though now would be a good time to request this:

I want to add a slider to RTAutoSprintEx for setting the FOV and the amount it changes when you sprint - this means I would need a slider that goes between 50 and 110 in 1 step increments, and one that goes between 1.0 to 2.0 in 0.05 step increments. Would it be possible to implement this for the rewrite?

**Comment by RuneMasterGaming** [comment]
It would definitely be possible. I'm very open to requests for UI components. I'm hoping to add quite a few different components for people to use.

**Comment by RuneMasterGaming** [comment]
https://user-images.githubusercontent.com/12521934/115093655-0b5aca00-9ee9-11eb-986f-9b710ca95c26.mp4

Done!
